rng default % For reproducibility
FitnessFunction = @ef_factor;
numberOfVariables = 25;
options = optimoptions('ga','PlotFcn',{['gaplotbestindiv','gaplotdistance']},...
                        'PopulationSize',50,'SelectionFcn','selectionroulette',...
                        'CrossoverFcn', 'crossovertwopoint', 'MaxGenerations',100,...
                        'MaxStallGenerations',15,'PopulationType','bitstring',...
                        'MutationFcn', {@mutationuniform, 0.05});
[x,fval] = ga(FitnessFunction,numberOfVariables,[],[],[],[],[],[],[],options);

function y = ef_factor(ch)
path(path,'/kuacc/apps/lumerical/2020a/api/matlab');
sim_file_path=('/kuacc/users/bebrem18/Documents/SERS'); % update this path to user's folder
sim_file_name=('50nmgold.fsp');
h=appopen('fdtd');
appputvar(h,'sim_file_path',sim_file_path);
appputvar(h,'sim_file_name',sim_file_name);
%Modify the pixel information and run the simulation
code=strcat('cd(sim_file_path);',...
'load(sim_file_name);',...
'switchtolayout;',...
'select("0");',...
'set("enabled",',num2str(ch(1)),');',...
'select("1");',...
'set("enabled",',num2str(ch(2)),');',...
'select("2");',...
'set("enabled",',num2str(ch(3)),');',...
'select("3");',...
'set("enabled",',num2str(ch(4)),');',...
'select("4");',...
'set("enabled",',num2str(ch(5)),');',...
'select("5");',...
'set("enabled",',num2str(ch(5)),');',...
'select("6");',...
'set("enabled",',num2str(ch(4)),');',...
'select("7");',...
'set("enabled",',num2str(ch(3)),');',...
'select("8");',...
'set("enabled",',num2str(ch(2)),');',...
'select("9");',...
'set("enabled",',num2str(ch(1)),');',...
'select("10");',...
'set("enabled",',num2str(ch(6)),');',...
'select("11");',...
'set("enabled",',num2str(ch(7)),');',...
'select("12");',...
'set("enabled",',num2str(ch(8)),');',...
'select("13");',...
'set("enabled",',num2str(ch(9)),');',...
'select("14");',...
'set("enabled",',num2str(ch(10)),');',...
'select("15");',...
'set("enabled",',num2str(ch(10)),');',...
'select("16");',...
'set("enabled",',num2str(ch(9)),');',...
'select("17");',...
'set("enabled",',num2str(ch(8)),');',...
'select("18");',...
'set("enabled",',num2str(ch(7)),');',...
'select("19");',...
'set("enabled",',num2str(ch(6)),');',...
'select("20");',...
'set("enabled",',num2str(ch(11)),');',...
'select("21");',...
'set("enabled",',num2str(ch(12)),');',...
'select("22");',...
'set("enabled",',num2str(ch(13)),');',...
'select("23");',...
'set("enabled",',num2str(ch(14)),');',...
'select("24");',...
'set("enabled",',num2str(ch(15)),');',...
'select("25");',...
'set("enabled",',num2str(ch(15)),');',...
'select("26");',...
'set("enabled",',num2str(ch(14)),');',...
'select("27");',...
'set("enabled",',num2str(ch(13)),');',...
'select("28");',...
'set("enabled",',num2str(ch(12)),');',...
'select("29");',...
'set("enabled",',num2str(ch(11)),');',...
'select("30");',...
'set("enabled",',num2str(ch(16)),');',...
'select("31");',...
'set("enabled",',num2str(ch(17)),');',...
'select("32");',...
'set("enabled",',num2str(ch(18)),');',...
'select("33");',...
'set("enabled",',num2str(ch(19)),');',...
'select("34");',...
'set("enabled",',num2str(ch(20)),');',...
'select("35");',...
'set("enabled",',num2str(ch(20)),');',...
'select("36");',...
'set("enabled",',num2str(ch(19)),');',...
'select("37");',...
'set("enabled",',num2str(ch(18)),');',...
'select("38");',...
'set("enabled",',num2str(ch(17)),');',...
'select("39");',...
'set("enabled",',num2str(ch(16)),');',...
'select("40");',...
'set("enabled",',num2str(ch(21)),');',...
'select("41");',...
'set("enabled",',num2str(ch(22)),');',...
'select("42");',...
'set("enabled",',num2str(ch(23)),');',...
'select("43");',...
'set("enabled",',num2str(ch(24)),');',...
'select("44");',...
'set("enabled",',num2str(ch(25)),');',...
'select("45");',...
'set("enabled",',num2str(ch(25)),');',...
'select("46");',...
'set("enabled",',num2str(ch(24)),');',...
'select("47");',...
'set("enabled",',num2str(ch(23)),');',...
'select("48");',...
'set("enabled",',num2str(ch(22)),');',...
'select("49");',...
'set("enabled",',num2str(ch(21)),');',...
'select("50");',...
'set("enabled",',num2str(ch(21)),');',...
'select("51");',...
'set("enabled",',num2str(ch(22)),');',...
'select("52");',...
'set("enabled",',num2str(ch(23)),');',...
'select("53");',...
'set("enabled",',num2str(ch(24)),');',...
'select("54");',...
'set("enabled",',num2str(ch(25)),');',...
'select("55");',...
'set("enabled",',num2str(ch(25)),');',...
'select("56");',...
'set("enabled",',num2str(ch(24)),');',...
'select("57");',...
'set("enabled",',num2str(ch(23)),');',...
'select("58");',...
'set("enabled",',num2str(ch(22)),');',...
'select("59");',...
'set("enabled",',num2str(ch(21)),');',...
'select("60");',...
'set("enabled",',num2str(ch(16)),');',...
'select("61");',...
'set("enabled",',num2str(ch(17)),');',...
'select("62");',...
'set("enabled",',num2str(ch(18)),');',...
'select("63");',...
'set("enabled",',num2str(ch(19)),');',...
'select("64");',...
'set("enabled",',num2str(ch(20)),');',...
'select("65");',...
'set("enabled",',num2str(ch(20)),');',...
'select("66");',...
'set("enabled",',num2str(ch(19)),');',...
'select("67");',...
'set("enabled",',num2str(ch(18)),');',...
'select("68");',...
'set("enabled",',num2str(ch(17)),');',...
'select("69");',...
'set("enabled",',num2str(ch(16)),');',...
'select("70");',...
'set("enabled",',num2str(ch(11)),');',...
'select("71");',...
'set("enabled",',num2str(ch(12)),');',...
'select("72");',...
'set("enabled",',num2str(ch(13)),');',...
'select("73");',...
'set("enabled",',num2str(ch(14)),');',...
'select("74");',...
'set("enabled",',num2str(ch(15)),');',...
'select("75");',...
'set("enabled",',num2str(ch(15)),');',...
'select("76");',...
'set("enabled",',num2str(ch(14)),');',...
'select("77");',...
'set("enabled",',num2str(ch(13)),');',...
'select("78");',...
'set("enabled",',num2str(ch(12)),');',...
'select("79");',...
'set("enabled",',num2str(ch(11)),');',...
'select("80");',...
'set("enabled",',num2str(ch(6)),');',...
'select("81");',...
'set("enabled",',num2str(ch(7)),');',...
'select("82");',...
'set("enabled",',num2str(ch(8)),');',...
'select("83");',...
'set("enabled",',num2str(ch(9)),');',...
'select("84");',...
'set("enabled",',num2str(ch(10)),');',...
'select("85");',...
'set("enabled",',num2str(ch(10)),');',...
'select("86");',...
'set("enabled",',num2str(ch(9)),');',...
'select("87");',...
'set("enabled",',num2str(ch(8)),');',...
'select("88");',...
'set("enabled",',num2str(ch(7)),');',...
'select("89");',...
'set("enabled",',num2str(ch(6)),');',...
'select("90");',...
'set("enabled",',num2str(ch(1)),');',...
'select("91");',...
'set("enabled",',num2str(ch(2)),');',...
'select("92");',...
'set("enabled",',num2str(ch(3)),');',...
'select("93");',...
'set("enabled",',num2str(ch(4)),');',...
'select("94");',...
'set("enabled",',num2str(ch(5)),');',...
'select("95");',...
'set("enabled",',num2str(ch(5)),');',...
'select("96");',...
'set("enabled",',num2str(ch(4)),');',...
'select("97");',...
'set("enabled",',num2str(ch(3)),');',...
'select("98");',...
'set("enabled",',num2str(ch(2)),');',...
'select("99");',...
'set("enabled",',num2str(ch(1)),');',...
'run;');
appevalscript(h,code);

%Get the E-field from XY power monitor
code=strcat('exy=getelectric("XY");');
appevalscript(h,code);

%Get the maximum e-field(figure of merit) from FDTD workspace to
%Matlab workspace
exy=appgetvar(h,'exy');
mxz=max((exy).^2);
EFxy = max(mxz(:));

%Get the average e-field(figure of merit) from FDTD workspace to
%Matlab workspace
% exy=appgetvar(h,'exy');
% mxz=mean((exy).^2);
% EFxy = mean(mxz(:));

% Multiply with -1 in order to maximize the result
y = (-1)*EFxy;
appclose(h);

end
